# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the local code to the container
COPY target/gerenciador-eventos-0.0.1-SNAPSHOT.jar /app

# Make port 9000 available to the world outside this container
EXPOSE 9000

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "gerenciador-eventos-0.0.1-SNAPSHOT.jar"]
