# Fase de construção
FROM maven:latest AS builder

WORKDIR /app

# Copiar o arquivo pom.xml para baixar as dependências
COPY pom.xml ./

# Fazer download das dependências Maven
RUN mvn dependency:go-offline -B

# Copiar o código-fonte completo
COPY src ./src

# Compilar o projeto e gerar o JAR
RUN mvn clean package -DskipTests

# Fase final
FROM openjdk:17-jdk-slim

# Criar um usuário não root para maior segurança
RUN useradd -m -s /bin/bash appuser

WORKDIR /app

# Copiar o JAR gerado na fase de construção
COPY --from=builder /app/target/*.jar app.jar

# Alterar o proprietário dos arquivos para o usuário não root
RUN chown -R appuser:appuser /app

# Trocar para o usuário não root
USER appuser

# Expor a porta onde a aplicação será executada
EXPOSE 9000

# Comando para iniciar a aplicação
CMD ["java", "-jar", "app.jar"]
