# Usar a imagem base do OpenJDK 17
FROM openjdk:17-jdk-slim

# Instalar Maven
RUN apt-get update && apt-get install -y maven

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar o arquivo pom.xml e os scripts do Maven para o diretório de trabalho
COPY pom.xml ./
COPY mvnw ./
COPY .mvn ./.mvn

# Garantir que o script mvnw tenha permissões de execução
RUN chmod +x mvnw

# Baixar as dependências necessárias para o Maven
RUN ./mvnw dependency:go-offline

# Copiar o código fonte para o container
COPY src ./src

# Executar o Maven para gerar o arquivo .jar
RUN ./mvnw clean package

# Verificar se o arquivo .jar foi gerado no diretório target
RUN ls -l ./target

# Expor a porta onde o app vai rodar
EXPOSE 9000

# Definir o comando para rodar o .jar
CMD ["java", "-jar", "./target/gerenciador-eventos-0.0.1-SNAPSHOT.jar"]
