import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ToastProvider} from "@/context/ToastContext";
import {AuthProvider} from "@/context/AuthContext";
import Header from "@/components/header/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <ToastProvider>
                <AuthProvider>
                    <Header />
                    {children}
                </AuthProvider>
            </ToastProvider>
        </body>
        </html>
    );
}
